title: Interpreted Dance
tagline: gettup get down
description: Blog about bear stuffs
#Comment out url when working locally to resolve base urls correctly
url: //jamison.dance

authors:
  jamison:
    bio: "Jamison cares about family and JavaScript programming and <a href=\"https://reactrally.com\">React Rally</a> and <a href=\"https://softskills.audio\">Soft Skills Engineering</a> and <a href=\"https://jsjabber.com\">JavaScript Jabber</a> and ğŸ‹ï¸ and ğŸ‚ and computing and business and <a href=\"https://fivestack.computer\">Fivestack</a> and the Dunning-Kreuger effect. He is a real human bean who you can reach on twitter."
    display_name: Jamison Dance
    gravatar: 6b3da28d67c0c30048665399688f0fdc
    email: hi@jamison.dance
    twitter: jergason
    github: jergason


# Owner/author information
owner:
  name: Jamison Dance
  email: hi@jamison.dance
  twitter: jergason
  github: jergason
  disqus: jergason
  # Plug in your disqus shortname!

sass:
  style: compressed


# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /about
    external: false
  - title: GitHub
    url: https://github.com/jergason
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Denver
future: true
highlighter: rouge
markdown:    redcarpet

permalink: /:month-:day-:year/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
